version: '2.4'

services:
  explore:
    # Autonomous exploration node
    container_name: explore
    build: .
    command: ros2 launch explore_lite explore.launch.py
    env_file:
      - environment.env
    volumes:
      - xplorervolume:/workspaces
  ## network_mode and ipc required for integration with real robot (UNIX only)
  # network_mode: host
  # ipc: host

  rostcp:
    # ROS-Unity integration node
    container_name: rostcp
    build: .
    command: ros2 run ros_tcp_endpoint default_server_endpoint --ros-args -p ROS_IP:=0.0.0.0
    env_file:
      - environment.env
    volumes:
      - xplorervolume:/workspaces
    ports:
      - "10000:10000"
      - "5005:5005"
  ## network_mode and ipc required for integration with real robot (UNIX only)
  # network_mode: host
  # ipc: host

  gazebo:
    # Gazebo simulation + rviz nodes
    container_name: gazebo
    build: .
    command: ros2 launch nav2_bringup tb3_simulation_launch.py slam:=True world:=/opt/ros/galactic/share/turtlebot3_gazebo/worlds/labyrinthe.world
    privileged: true
    env_file:
      - environment.env
    volumes:
      - xplorervolume:/workspaces
      - /tmp/.X11-unix:/tmp/.X11-unix

volumes:
  xplorervolume: # Fixes Linux + Docker GUI problems
